name: openthread-border-router
version: "0.1"
# license: TBA
summary: Snap packaging of OpenThread Border Router project for POSIX systems
description: Refer to https://snapcraft.io/openthread-border-router

base: core22

architectures:
  - build-on: amd64
  - build-on: arm64

grade: devel
confinement: devmode

apps:
  otbr-setup:
    command: bin/otbr-setup.sh
    daemon: oneshot
    install-mode: enable
    restart-delay: 10s

  otbr-agent:
    after: [otbr-setup]
    command: bin/otbr-agent
    daemon: simple
    install-mode: enable
    restart-delay: 10s

  otbr-web:
    after: [otbr-setup]
    command: bin/otbr-web
    daemon: simple
    install-mode: enable
    restart-delay: 3s

  otbr-firewall:
    after: [otbr-setup]
    command: bin/otbr-firewall start
    daemon: simple
    install-mode: disable
    restart-delay: 3s

  ot-ctl:
    after: [otbr-setup]
    command: bin/ot-ctl
    daemon: simple
    install-mode: enable
    restart-delay: 3s

  otbr-nat44:
    after: [otbr-setup]
    command: bin/otbr-nat44 start
    daemon: simple
    install-mode: enable
    restart-delay: 10s
  
parts:
  openthread-deps:
    source: https://github.com/openthread/ot-br-posix.git
    source-tag: thread-reference-20230119
    source-depth: 1
    plugin: cmake
    build-snaps:
      - cmake
    build-packages: 
      - wget
      - libreadline-dev
      - libncurses-dev
      - build-essential
      - ninja-build
      - libcpputest-dev
      - libdbus-1-dev
      - libavahi-common-dev 
      - libavahi-client-dev
      - libjsoncpp-dev
      - libprotobuf-dev
      - protobuf-compiler

    stage-packages:
      - iproute2
      - iputils-ping
      - rsyslog
      - libavahi-client3
      - iptables
      - ipset
      - dnsmasq-base
      - dnsmasq-utils
      - network-manager
      - dhcpcd5
      - libatm1

    override-build: |
      craftctl default
      cd $CRAFT_PART_BUILD

      # Install the mDNSResponder library on Linux system
      MDNS_RESPONDER_SOURCE_NAME=mDNSResponder-1310.80.1
      wget --no-check-certificate https://github.com/apple-oss-distributions/mDNSResponder/archive/refs/tags/$MDNS_RESPONDER_SOURCE_NAME.tar.gz
      mkdir -p $MDNS_RESPONDER_SOURCE_NAME
      tar xvf $MDNS_RESPONDER_SOURCE_NAME.tar.gz -C $MDNS_RESPONDER_SOURCE_NAME --strip-components=1
      cd $CRAFT_PART_BUILD/$MDNS_RESPONDER_SOURCE_NAME/Clients
      sed -i '/#include <ctype.h>/a #include <stdarg.h>' dns-sd.c
      sed -i '/#include <ctype.h>/a #include <sys/param.h>' dns-sd.c
      cd $CRAFT_PART_BUILD/$MDNS_RESPONDER_SOURCE_NAME/mDNSPosix
      make os=linux
      make install os=linux

  ot-br-posix:
    after: [openthread-deps]
    plugin: nil
    source: local/bin
    build-packages: 
      - sudo
      - lsb-release
      - kmod
      - iptables
      - xtables-addons-common
    override-build: |
      craftctl default
      
      cd $CRAFT_PART_BUILD

      cp -vf ./otbr-build.sh ../../openthread-deps/src/script
      cd ../../openthread-deps

      # This script builds and installs border router and dependencies.
      chmod +x ./src/script/otbr-build.sh
      ./src/script/otbr-build.sh

      # Todo: install -DT "$CRAFT_PART_SRC/LICENSE" "$CRAFT_PART_INSTALL/usr/share/doc/ot-br-posix/LICENSE"
      # Copy library
      mkdir -p $CRAFT_PART_INSTALL/usr/lib/
      mkdir -p $CRAFT_PART_INSTALL/bin
      mkdir -p $CRAFT_PART_INSTALL/lib/lsb/
      mkdir -p $CRAFT_PART_INSTALL/lib/init/
      cp -v /usr/lib/libdns_sd.so $CRAFT_PART_INSTALL/usr/lib/
      cp -v /lib/lsb/init-functions $CRAFT_PART_INSTALL/lib/lsb/
      cp -v /lib/init/vars.sh $CRAFT_PART_INSTALL/lib/init/

      # Configure and copy executables
      
      pwd
      ls
      cp ./build/src/agent/otbr-agent $CRAFT_PART_INSTALL/bin/
      # cp ./build/otbr/src/web/otbr-web $CRAFT_PART_INSTALL/bin/
      cp ./build/third_party/openthread/repo/src/posix/ot-ctl $CRAFT_PART_INSTALL/bin/

      chmod a+x ./src/script/otbr-firewall
      cp ./src/script/otbr-firewall $CRAFT_PART_INSTALL/bin/

      # cp -v /etc/init.d/otbr-nat44 $CRAFT_PART_INSTALL/bin/

  runtime-helpers:
    plugin: dump
    source: local/runtime-helpers
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp -v otbr-setup.sh $CRAFT_PART_INSTALL/bin
      cp -v install-otbr-firewall.sh $CRAFT_PART_INSTALL/bin

