name: openthread-border-router
# license: TBA
summary: Snap packaging of OpenThread Border Router project for POSIX systems
description: Refer to https://snapcraft.io/openthread-border-router
adopt-info: otbr

base: core22

architectures:
  - build-on: amd64
  - build-on: arm64

grade: devel
confinement: strict


slots:
  # This adds the needed security policy for the communication.
  # It is also used for communication between third-party apps and the OTBR agent for Thread networking
  dbus-wpan0:
    interface: dbus
    bus: system
    name: io.openthread.BorderRouter.wpan0

layout:
  /usr/share/otbr-web/frontend:
    symlink: $SNAP/usr/share/otbr-web/frontend
  # This is the default OT_POSIX_SETTINGS_PATH
  /var/lib/thread:
    symlink: $SNAP_COMMON/thread-data

# hooks:
#     install:
#         plugs: [network]

apps:
  otbr-setup:
    command: bin/otbr-setup.sh
    daemon: oneshot
    install-mode: disable
    plugs:
      - network
      - network-bind
      - network-control
      - firewall-control

  otbr-agent:
    after:
      - otbr-setup
    command: bin/otbr-agent.sh
    daemon: simple
    install-mode: disable
    # restart-delay: 10s
    plugs: 
      - network 
      - network-bind
      - network-control
      - avahi-control
      - firewall-control
      # Acess bluetooth for device discovery over BLE
      - bluetooth-control
      - bluez
      # Access to RCP USB devices
      - raw-usb

  # Web GUI
  # The default port is 80
  otbr-web:
    after: 
      - otbr-agent
    command: bin/otbr-web
    daemon: simple
    install-mode: disable
    # restart-delay: 3s
    plugs:
      - network
      - network-bind
    

  ot-ctl:
    command: bin/ot-ctl
  
  pskc:
    command: bin/pskc

  steering-data:
    command: bin/steering-data

parts:
  build-bin:
    plugin: nil
    source: snap/local/build/bin
    override-build: |
      # Resources needed for the build
      mkdir -p $SNAPCRAFT_STAGE/snap/bin
      cp -v * $SNAPCRAFT_STAGE/snap/bin
  
  stage-bin:
    plugin: nil
    source: snap/local/stage/bin
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -v * $CRAFT_PART_INSTALL/bin/

  otbr:
    after:
      - build-bin
    source: https://github.com/openthread/ot-br-posix.git
    source-tag: thread-reference-20230119
    source-depth: 1
    plugin: nil
    build-packages: 
      - libreadline-dev
      - libncurses-dev
      - build-essential
      - ninja-build
      - libcpputest-dev
      - libdbus-1-dev
      - libavahi-common-dev 
      - libavahi-client-dev
      - libjsoncpp-dev
      - libprotobuf-dev
      - protobuf-compiler
      - lsb-release
      - cmake
      # - sudo
      # Boost
      - libboost-dev
      - libboost-filesystem-dev
      - libboost-system-dev
      # web dependencies
      - nodejs
      - npm
    stage-packages:
      - iproute2
      - iputils-ping
      - rsyslog
      - libavahi-client3
      - iptables
      - ipset
      - dnsmasq-base
      - dnsmasq-utils
      - network-manager
      - dhcpcd5
      - libatm1
      - libjsoncpp-dev
    override-build: |
      craftctl set version="$(git describe --tags)+snap"

      # Setup scripts
      # Remove sudo from scripts
      find ./script -type f -exec sed -i 's/sudo //g' {} +
      # TODO: This copies everything, even though most aren't required
      cp -vr ./script $CRAFT_PART_INSTALL/bin/
      chmod +x $CRAFT_PART_INSTALL/bin/script/otbr-firewall

      SNAP_RUN_OTBR="/run/snap.$CRAFT_PROJECT_NAME/openthread-%s"

      OTBR_OPTIONS="-DCMAKE_INSTALL_LIBDIR=${SNAPCRAFT_PART_INSTALL}/lib/"
      OTBR_OPTIONS+=" -DCMAKE_INSTALL_SYSCONFDIR=${SNAPCRAFT_PART_INSTALL}/etc/"
      OTBR_OPTIONS+=" -DOT_CFLAGS=-DOPENTHREAD_POSIX_CONFIG_DAEMON_SOCKET_BASENAME=\"$SNAP_RUN_OTBR\""
      OTBR_OPTIONS+=" -DWEB_CFLAGS=-DOPENTHREAD_POSIX_DAEMON_SOCKET_NAME=\"$SNAP_RUN_OTBR.sock\""
      # OTBR_OPTIONS+=" -DCMAKE_BUILD_TYPE=Debug"
      
      # Add the compile option to override the posix socket
      sed -i '/^target_compile_options/a ${WEB_CFLAGS}' src/web/CMakeLists.txt

      # TODO: Avoid setting INFRA_IF_NAME here
      # The value is passed to cmake-build and then added to /etc/default/otbr-agent
      # but /etc/default/otbr-agent is not used in this snap.
      OTBR_OPTIONS=$OTBR_OPTIONS \
      PLATFORM=ubuntu \
      BUILD_DIR=$PWD/build \
      INFRA_IF_NAME=wlan0 \
      OTBR_MDNS=avahi \
        $SNAPCRAFT_STAGE/snap/bin/otbr-build.sh
      
      # Binary distributions
      cp -v ./build/otbr/src/web/otbr-web \
            ./build/otbr/src/agent/otbr-agent \
            ./build/otbr/third_party/openthread/repo/src/posix/ot-ctl \
            ./build/otbr/tools/pskc \
            ./build/otbr/tools/steering-data \
            $CRAFT_PART_INSTALL/bin/

      # Static web resources
      # See the layout mapping on top
      mkdir -p $CRAFT_PART_INSTALL/usr/share/otbr-web
      cp -vr /usr/share/otbr-web/frontend \
             $CRAFT_PART_INSTALL/usr/share/otbr-web/

      craftctl default

  license:
    plugin: nil
    source: .
    override-build: |
      install -DTv LICENSE $CRAFT_PART_INSTALL/usr/share/doc/LICENSE
