name: openthread-border-router
version: git
# license: TBA
summary: Snap packaging of OpenThread Border Router project for POSIX systems
description: Refer to https://snapcraft.io/openthread-border-router

base: core22

architectures:
  - build-on: amd64
  - build-on: arm64

grade: devel
confinement: devmode

lint:
  ignore:
    - library:
      - $SNAP/lib/libdbus-1.so.3.19.13

apps:
  otbr-agent:
    command: bin/otbr-agent
    daemon: simple
    install-mode: enable
    restart-delay: 10s
    plugs: 
      - network
      - network-bind
      - bluez
      - avahi-control
  otbr-web:
    command: bin/otbr-web
    daemon: simple
    install-mode: enable
    restart-delay: 3s
    plugs: 
      - network
      - network-bind
      - bluez
      - avahi-control
  otbr-firewall:
    command: bin/otbr-firewall start
    daemon: simple
    install-mode: enable
    restart-delay: 3s
    plugs: 
      - network
      - network-bind
      - bluez
      - avahi-control
  ot-ctl:
    command: bin/ot-ctl
    daemon: simple
    install-mode: enable
    restart-delay: 3s
    plugs: 
      - home
      - network
      - network-bind
  otbr-nat44:
    command: bin/otbr-nat44 start
    daemon: simple
    install-mode: enable
    restart-delay: 10s
    plugs: 
      - network
      - network-bind
  
parts:
  openthread-deps:
    source: https://github.com/openthread/ot-br-posix.git
    source-branch: main
    source-depth: 1
    plugin: cmake
    build-snaps:
      - cmake
    build-packages: 
      - wget
      - libreadline-dev
      - libncurses-dev
      - build-essential
      - ninja-build
      - libcpputest-dev
      - libdbus-1-dev
      - libavahi-common-dev 
      - libavahi-client-dev
      - libjsoncpp-dev
      - libprotobuf-dev
      - protobuf-compiler

    stage-packages:
      - iproute2
      - iputils-ping
      - rsyslog
      - libavahi-client3
      - iptables
      - ipset
      - dnsmasq-base
      - dnsmasq-utils
      - network-manager
      - dhcpcd5
      - libatm1

    override-build: |
      craftctl default
      cd $CRAFT_PART_BUILD

      # Install the mDNSResponder library on Linux system
      MDNS_RESPONDER_SOURCE_NAME=mDNSResponder-1310.80.1
      wget --no-check-certificate https://github.com/apple-oss-distributions/mDNSResponder/archive/refs/tags/$MDNS_RESPONDER_SOURCE_NAME.tar.gz
      mkdir -p $MDNS_RESPONDER_SOURCE_NAME
      tar xvf $MDNS_RESPONDER_SOURCE_NAME.tar.gz -C $MDNS_RESPONDER_SOURCE_NAME --strip-components=1
      cd $CRAFT_PART_BUILD/$MDNS_RESPONDER_SOURCE_NAME/Clients
      sed -i '/#include <ctype.h>/a #include <stdarg.h>' dns-sd.c
      sed -i '/#include <ctype.h>/a #include <sys/param.h>' dns-sd.c
      cd $CRAFT_PART_BUILD/$MDNS_RESPONDER_SOURCE_NAME/mDNSPosix
      make os=linux
      make install os=linux

  ot-br-posix:
    after: [openthread-deps]
    plugin: nil
    stage-packages:
      - libjsoncpp-dev
      - libavahi-client3
      - protobuf-compiler
      - ipset
      
    # build-environment: [INFRA_IF_NAME: eth0] 
    override-build: |
      craftctl default
      cd ../../openthread-deps/src

      # Compile and install OTBR
      INFRA_IF_NAME=eth0 BACKBONE_ROUTER=0 ./script/setup

      # install -DT "$CRAFT_PART_SRC/LICENSE" "$CRAFT_PART_INSTALL/usr/share/doc/ot-br-posix/LICENSE"
      mkdir -p $CRAFT_PART_INSTALL/bin

      # Copy library
      cp -v /usr/lib/libdns_sd.so $CRAFT_PART_INSTALL/usr/lib/

      # Configure and copy executables
      cp ./build/otbr/src/agent/otbr-agent $CRAFT_PART_INSTALL/bin/
      cp ./build/otbr/src/web/otbr-web $CRAFT_PART_INSTALL/bin/
      cp ./build/otbr/third_party/openthread/repo/src/posix/ot-ctl $CRAFT_PART_INSTALL/bin/

      chmod a+x ./script/otbr-firewall
      cp ./script/otbr-firewall $CRAFT_PART_INSTALL/bin/

      cp -v /etc/init.d/otbr-nat44 $CRAFT_PART_INSTALL/bin/


