name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    name: Build, Upload, Test
    strategy:
      fail-fast: false
      matrix:
        runs:
          - architecture: amd64
            runner: ubuntu-24.04
            run_tests: true
          - architecture: arm64
            runner: ubuntu-24.04-arm
            run_tests: true
    runs-on: ${{ matrix.runs.runner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Build snap
        uses: snapcore/action-build@v1
        id: snapcraft

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.snapcraft.outputs.snap }}
          path: ${{ steps.snapcraft.outputs.snap }}
          if-no-files-found: error

      - name: Setup Go
        if: matrix.runs.run_tests
        uses: actions/setup-go@v6
        with:
          go-version: '1.*'
          cache: false

      - name: Run tests
        if: matrix.runs.run_tests
        shell: bash
        working-directory: tests
        env:
          SKIP_TEARDOWN_REMOVAL: true
          LOCAL_SERVICE_SNAP: ../${{ steps.snapcraft.outputs.snap }}
          INFRA_IF: "eth0"
        run: |
          # Override the infrastructure interface for GitHub Action
          go test -failfast -p 1 -timeout 30m -v

      - name: Upload snap logs
        if: always() && matrix.runs.run_tests
        uses: actions/upload-artifact@v7
        with:
          name: logs-${{ matrix.runs.architecture }}
          path: tests/*.log
