#!/bin/bash -e

TAG="$SNAP_NAME.default-configure"

logger --tag=$TAG "Start"

logger --tag=$TAG "'autostart':"$(snapctl get autostart)""

if [ "$autostart" = true ]; then
    logger --tag=$TAG "'autostart' is enabled: starting and enabling openthread-border-router services."
    snapctl start --enable openthread-border-router  
else
    logger --tag=$TAG --stderr "Invalid value for 'autostart': $autostart"
    exit 1
fi

logger --tag=$TAG "End"
