#!/bin/bash -e

TAG="$SNAP_NAME.default-configure"

logger --tag=$TAG "Start"

autostart="$(snapctl get autostart)"

if [ -z "$autostart" ]; then
    logger --tag=$TAG "'autostart' is unset."
elif [ "$autostart" = true ]; then
    logger --tag=$TAG "'autostart' is enabled ($autostart): starting and enabling openthread-border-router services."
    snapctl start --enable openthread-border-router
elif [ "$autostart" = false ]; then
    logger --tag=$TAG "'autostart' is disabled ($autostart)."    
else
    logger --tag=$TAG --stderr "Invalid value for 'autostart': $autostart"
fi

logger --tag=$TAG "End"
