#!/bin/bash -e

TAG="snap.$SNAP_NAME.hook.install"

logger --tag=$TAG "Setting default snap options"
exec 2> >(logger --tag="$TAG")
set -x
snapctl set infra-if=wlan0
snapctl set thread-if=wpan0
snapctl set radio-url="spinel+hdlc+uart:///dev/ttyACM0"
snapctl set autostart=false
snapctl set source=install
set +x

mkdir -p $SNAP_COMMON/thread-data
