#!/bin/bash -e

TAG="$SNAP_NAME.hook.install"

logger --tag=$TAG "Setting default snap options"
# Redirect standard error to syslog. This is to capture the xtrace output.
exec 2> >(logger --tag="$TAG")
set -x
snapctl set infra-if=wlan0
snapctl set thread-if=wpan0
snapctl set radio-url="spinel+hdlc+uart:///dev/ttyACM0"
snapctl set autostart=false
snapctl set webgui-listen-address="::"
snapctl set webgui-port=80
set +x

THREAD_DATA=$SNAP_COMMON/thread-data

logger --tag=$TAG "Create directory for thread data: $THREAD_DATA"
mkdir -p $THREAD_DATA
