#!/bin/bash -e

TAG="$SNAP_NAME.hook.remove"

###############################################################################
logger --tag=$TAG "Remove the firewall config"
$SNAP/bin/script/otbr-firewall stop


