#!/bin/bash -e

TAG="$SNAP_NAME.remove"

logger --tag=$TAG "Start"


###############################################################################
logger --tag=$TAG "Remove the firewall config"
$SNAP/bin/script/otbr-firewall stop



rm -f /run/snap.$SNAP_NAME

logger --tag=$TAG "End"
